# Generated by Django 4.1.3 on 2022-12-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('seats_number', models.SmallIntegerField()),
                ('projector', models.BooleanField(default=False)),
            ],
        ),
    ]
